spring.application.name=notification

spring.kafka.bootstrap-servers=${KAFKA_URL:my-kafka.kafka.svc.cluster.local:9092}

# 컨슈머 설정
spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.datasource.url=jdbc:mariadb://${DB_URL:localhost}:3306/${DB_NAME:notificationdb}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:password}
