spring.application.name=board-backend
# MariaDB
spring.datasource.url=jdbc:mariadb://terraform-20260112034418401700000001.cfoe28g0e5qp.ap-northeast-2.rds.amazonaws.com:3306/board
spring.datasource.username=admin
spring.datasource.password=password123
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Kafka
spring.kafka.bootstrap-servers=my-kafka.kafka.svc.cluster.10.21.1.202:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.acks=1
spring.kafka.producer.retries=3
